### ISSUE TITLE
Please Update AKBottomNavigation2

### ISSUE THREAD

**Issue by kulothunganug** [quitegreensky/akivymd#13]
please make the `AKBottomNavigation2` and `Button_Item` depends on `ScreenManager` and `Screen`

### Example:
this code works like
```yaml
<Root>:

    AKBottomNavigation2:

        Button_Item:
            name: "screen 1"

            YourContent:

        Button_Item:
            name: "screen 2"

            YourContent:

        Button_Item:
            name: "screen 3"

            YourContent:
```
this
```yaml
<Root>:

    ScreenManager:

        Screen:
            name: "screen 1"

            YourContent:

        Screen:
            name: "screen 2"

            YourContent:

        Screen:
            name: "screen 3"

            YourContent:
```
